# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.student import Student  # noqa: F401,E501
from swagger_server import util


class Asignacion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, oscuridad: List[Student]=None, luz: List[Student]=None, fuego: List[Student]=None, agua: List[Student]=None, viento: List[Student]=None, tierra: List[Student]=None):  # noqa: E501
        """Asignacion - a model defined in Swagger

        :param oscuridad: The oscuridad of this Asignacion.  # noqa: E501
        :type oscuridad: List[Student]
        :param luz: The luz of this Asignacion.  # noqa: E501
        :type luz: List[Student]
        :param fuego: The fuego of this Asignacion.  # noqa: E501
        :type fuego: List[Student]
        :param agua: The agua of this Asignacion.  # noqa: E501
        :type agua: List[Student]
        :param viento: The viento of this Asignacion.  # noqa: E501
        :type viento: List[Student]
        :param tierra: The tierra of this Asignacion.  # noqa: E501
        :type tierra: List[Student]
        """
        self.swagger_types = {
            'oscuridad': List[Student],
            'luz': List[Student],
            'fuego': List[Student],
            'agua': List[Student],
            'viento': List[Student],
            'tierra': List[Student]
        }

        self.attribute_map = {
            'oscuridad': 'Oscuridad',
            'luz': 'Luz',
            'fuego': 'Fuego',
            'agua': 'Agua',
            'viento': 'Viento',
            'tierra': 'Tierra'
        }
        self._oscuridad = oscuridad
        self._luz = luz
        self._fuego = fuego
        self._agua = agua
        self._viento = viento
        self._tierra = tierra

    @classmethod
    def from_dict(cls, dikt) -> 'Asignacion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asignacion of this Asignacion.  # noqa: E501
        :rtype: Asignacion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oscuridad(self) -> List[Student]:
        """Gets the oscuridad of this Asignacion.


        :return: The oscuridad of this Asignacion.
        :rtype: List[Student]
        """
        return self._oscuridad

    @oscuridad.setter
    def oscuridad(self, oscuridad: List[Student]):
        """Sets the oscuridad of this Asignacion.


        :param oscuridad: The oscuridad of this Asignacion.
        :type oscuridad: List[Student]
        """

        self._oscuridad = oscuridad

    @property
    def luz(self) -> List[Student]:
        """Gets the luz of this Asignacion.


        :return: The luz of this Asignacion.
        :rtype: List[Student]
        """
        return self._luz

    @luz.setter
    def luz(self, luz: List[Student]):
        """Sets the luz of this Asignacion.


        :param luz: The luz of this Asignacion.
        :type luz: List[Student]
        """

        self._luz = luz

    @property
    def fuego(self) -> List[Student]:
        """Gets the fuego of this Asignacion.


        :return: The fuego of this Asignacion.
        :rtype: List[Student]
        """
        return self._fuego

    @fuego.setter
    def fuego(self, fuego: List[Student]):
        """Sets the fuego of this Asignacion.


        :param fuego: The fuego of this Asignacion.
        :type fuego: List[Student]
        """

        self._fuego = fuego

    @property
    def agua(self) -> List[Student]:
        """Gets the agua of this Asignacion.


        :return: The agua of this Asignacion.
        :rtype: List[Student]
        """
        return self._agua

    @agua.setter
    def agua(self, agua: List[Student]):
        """Sets the agua of this Asignacion.


        :param agua: The agua of this Asignacion.
        :type agua: List[Student]
        """

        self._agua = agua

    @property
    def viento(self) -> List[Student]:
        """Gets the viento of this Asignacion.


        :return: The viento of this Asignacion.
        :rtype: List[Student]
        """
        return self._viento

    @viento.setter
    def viento(self, viento: List[Student]):
        """Sets the viento of this Asignacion.


        :param viento: The viento of this Asignacion.
        :type viento: List[Student]
        """

        self._viento = viento

    @property
    def tierra(self) -> List[Student]:
        """Gets the tierra of this Asignacion.


        :return: The tierra of this Asignacion.
        :rtype: List[Student]
        """
        return self._tierra

    @tierra.setter
    def tierra(self, tierra: List[Student]):
        """Sets the tierra of this Asignacion.


        :param tierra: The tierra of this Asignacion.
        :type tierra: List[Student]
        """

        self._tierra = tierra
